#!/bin/bash
#
# Comment, .env, file utils

#######################################
# Delete some line in bash style comment # started.
# Globals:
#   None
# Arguments:
#   Stdout to delete comment ,a path. this param 
# Outputs:
#   Writes not stared bash style comment # line to stdout
# Returns:
#   0 if thing was deleted, non-zero on error.
# Example:
#   cat file | eraze_comment_line -
#   eraze_comment_line file
#######################################
function eraze_comment_line {
  local filepath=$1
  # contains -
  if [ -z $filepath ]; then
    filepath=-
  fi

  cat $filepath | sed 's/# .*$//'
}

#######################################
# Delete some line in bash style comment # started.
# Globals:
#   None
# Arguments:
#   Stdout to delete comment ,a path. this param 
# Outputs:
#   export VARIABLE_NAME=VARIABLE list
# Returns:
#   0 if thing was deleted, non-zero on error.
# Example:
#   cat file | convert_export_line -
#   convert_export_line file
#######################################
function convert_export_line {

  local filepath=$1
  # contains -
  if [ -z $filepath ]; then
    filepath=-
  fi
  eraze_comment_line $filepath | xargs -I {} echo export {}
}

#######################################
# load .env file. set your environment variable.
# Globals:
#   None
# Arguments:
#   load csv file ,a path.
# Outputs:
#   None
# Returns:
#   0 if thing was deleted, non-zero on error.
# Example:
#   cat .env | load_env
#   load_env .env
#######################################
function load_env {

  for arg in "$@"; do
    case "$arg" in
      -h|--help)
        function usage() {
          cat 1>&2 << END
load_env
output search engine setting

USAGE:
    load_env [FLAGS] [OPTIONS]

FLAGS:
    -h, --help              Prints help information

OPTIONS:
    --debug                 Set bash debug Option
END
          unset -f usage
        }
        usage
        return
        ;;
      --debug)
        # set debug
        set -x
        trap "
          set +x
          trap - RETURN
        " RETURN
        ;;
      *)
        ;;
    esac
  done

  local filepath=$1
  # if you ,use pipe line value.
  if [ -z $filepath ]; then
    echo 'you send parameter.' >&2
    return 1
  fi
  # eval "$(cat $1 | sed 's/# .*$//' | xargs -I {} echo export {};)"
  eval "$(cat $filepath | convert_export_line;)"
}
