#!/bin/bash
#
# gnu command util.

#######################################
# write stderr syntax. google style(https://google.github.io/styleguide/shellguide.html)
# Globals:
#   LOGFORMAT
# Arguments:
#   All.
# Outputs:
#   format 
# Returns:
#   0 if thing was set alias, non-zero on error.
# Example:
#   md2epub "Unable to do_something"  # => you use use sed
#######################################
function md2epub() {

  if ! type "pandoc" > /dev/null; then
    echo "pandoc is not exists. install pandoc!" >&2
    return 1
  fi
  local i
  local title
  local css
  local cover
  local new_array=( $@ )
  for ((i=0;i<$#;i++)); do
    if [ "${new_array[$i]}" = "--title" ]; then
      title=${new_array[$(($i+1))]}
      # if next index start '-', this value is option.
      if echo $title | grep ^- > /dev/null; then
        echo "set title txt!" >&2
        return 1
      fi
      unset new_array[$i] new_array[$(($i + 1))]
    fi
    if [ "${new_array[$i]}" = "--css" ]; then
      css=${new_array[$(($i+1))]}
      # if next index start '-', this value is option.
      if echo $css | grep ^- > /dev/null; then
        echo "set css!" >&2
        return 1
      fi
      unset new_array[$i] new_array[$(($i + 1))]
    fi
    if [ "${new_array[$i]}" = "--cover" ]; then
      cover=${new_array[$(($i+1))]}
      # if next index start '-', this value is option.
      if echo $cover | grep ^- > /dev/null; then
        echo "set cover!" >&2
        return 1
      fi
      unset new_array[$i] new_array[$(($i + 1))]
    fi
    if [ "${new_array[$i]}" = "--help" ] || [ "${new_array[$i]}" = "-h" ]; then

      function usage() {
        # あとで | help_fmtみたいな関数を作っておく。
        cat 1>&2 "
          md2epub
          output search engine setting

          USAGE:
              md2epub [FLAGS] [OPTIONS]

          FLAGS:
              --title                 Show usable search engines.
              --css                   using css 
              --cover                 using css 
              -h, --help              Prints help information

          OPTIONS:
              --debug                 Set bash debug Option
        "
        unset -f usage
      }
      return
    fi
  done

  local manuscript=${new_array[@]}
  
  local out=${manuscript//\.md/\.epub}
  pandoc -f markdown \
    -t epub3 \
    $manuscript \
    $title \
    -o $out \
    --css $css \
    --toc --toc-depth=2 \
    --epub-cover-image=$cover
}
