#!/bin/bash
#
# gnu command util.

#######################################
# output os_type
# Globals:
#   None
# Arguments:
#   None
# Outputs:
#   os_type
# Returns:
#   0 if specialize os, non-zero unknown os.
# Example:
#   read_function # => source ~/bash/function/*
#######################################
function read_function {

  # sourceが実行されたら.になるので、困る。
  # sourceコマンド実行前提のものにはdirname自体がよくない可能性。
  local function_dir=$HOME/bash/function

  eval "$(
    ls ${function_dir} |
    grep -v .md |
    grep -v read_function |
    xargs -I {} echo source ${function_dir}/{};
  )"
  unset -f read_function
}

read_function
