[package]
name = "example"
version = "0.1.0"
authors = ["KatsutoshiOtogawa <13373011+KatsutoshiOtogawa@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
