name: Bash

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: add path
      run: echo "bash/bin" >> $GITHUB_PATH
    - name: add path bash/bin/gnu
      run: echo "bash/bin/gnu" >> $GITHUB_PATH
    - name: add path bash/bin/search_engin
      run: echo "bash/bin/search_engine" >> $GITHUB_PATH
    - name: add path bash/bin/build_support
      run: echo "bash/bin/build_support" >> $GITHUB_PATH
    - name: add permission
      run: chmod u+x bash/bin/check_bash_version
    - name: check bash version
      run: check_bash_version
#     - name: Test
#       run: bash/bin/
    # package project files
    - name: compressive archive
      run: tar czvf bin.tar.gz bash/bin
    - name: staging
      run: mkdir staging && mv bin.tar.gz staging/
    - uses: actions/upload-artifact@v2
      with:
        name: bash
        path: staging
