name: Bash

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: add path
      run: echo "bash/bin" >> $GITHUB_PATH
    - name: add path bash/bin/search_engin
      run: echo "bash/bin/search_engine" >> $GITHUB_PATH
    - name: add path bash/bin/build_support
      run: echo "bash/bin/build_support" >> $GITHUB_PATH
    # add exec
    - name: add permission
      run: chmod -R u+x bash/bin
    - name: check bash version
      run: check_bash_version
    - name: outinfo
      run: LOGFORMAT="%Y-%m-%dT%H:%M:%S%z" outinfo

#     - name: Test
#       run: bash/bin/
    # package project files
    - name: compressive archive
      run: tar czvf bash_script.tar.gz bash/bin bash/function
    - name: staging
      run: mkdir staging && mv bash_script.tar.gz staging/
    - uses: actions/upload-artifact@v2
      with:
        name: bash_script
        path: staging
