name: Bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

#     - name: Test
#       run: bash/bin/
    # package project files
    - name: compressive archive
      run: tar czvf bin.tar.gz bash/bin
    - name: staging
      run: mkdir staging && mv bin.tar.gz staging/
    - uses: actions/upload-artifact@v2
      with:
        name: bash
        path: staging
