name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.16

#     - name: Build
#       run: go build -v ./...

#     - name: Test
#       run: go test -v ./...
  
    # package project files
    - name: compressive archive
      run: tar czvf bin.tar.gz bash/bin
    - name: staging
      run: mkdir staging && mv bin.tar.gz staging/
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
